### PR TITLE
Direction to start location

### PR DESCRIPTION
**Pull request by Mr-Groch**
Hi pulce, my friends asked me to add start location direction indicator. I've made it as much non-invasive as possible (small teardrop icon at top of the direction indicator). 

It will show after flight start is detected or logger was manually started and it will indicate direction to start location relative to current flight direction.

It is still work-in-progress (or in testing) so I've made this PR as draft.

Oh, I've also fixed swipe-to-dismiss - it is blocked now properly (I hope...)

IMG-20210613-011527

### CODE REVIEW

**Comment by pulce** [comment]
Hey Mr-Groch,
sorry for the late reply, I was busy and somewhat forgot that notification.
Nice thing, I'm happy that there is still progress in Wristglider. I'll merge to master of course. Unfortunately I changed my computer recently and have not yet set up android development. Thus it will probably take a while until I can deliver a new version for playstore. Hope that is OK for you, probably you can deliver out an apk to your friend?

**Comment by Mr-Groch** [comment]
Thanks, yes, I've shared apk file already for testing. I'm also working on another branch to support watch built-in barometric sensor. but this will took some time to finish. I've also doesn't have much spare time ;)

**Comment by pulce** [comment]
Hey, thanks again for the commits! I've finally pushed a new version to playstore. Took 5 days to review, and I had to switch to app bundle instead of separate apks for wear 1 and 2. With that app bundle I'm having issues that the app doesn't get installed on the watch. Google and their constant changes are somewhat annoying when one doesn't do android stuff regularly.

Does everything in the playstore version work for you as expected?

As I see that you are still very active developing that app (much more than me): would you want to publish a playstore version? Just a thought, let me know what you think.

Cheers :)

**Comment by Mr-Groch** [comment]
Hi, sorry for the long silence. I have little free time at the moment... Thanks for publishing to Google Play Store. I haven't published yet nothing, so I don't know the procedure :) Can you push to this repo changes for new app bundle procedure so I can sync to it and apply to my branch with Vario changes?

**Comment by pulce** [comment]
Never mind the silence, I also have too much to do at the moment, luckily part of that is flying :)
I did not really do any code changes (except changing myVersionCode=30 and myVersionNumber="0.5.1"), the app bundle deployment can be done in Android Studio. I'd push that, but I also messed up my local git repo...

Another thing: one user reported a general problem that I could reproduce in the emulator: in very new Android versions it seems to be forbidden to write to local storage. I think Google wants to harden Android in terms of security. So as soon as one pulls a log from the watch, the app crashes. So one would have to redisign the way logs are stored.

I feel a bit sad to give up that project, but on the other hand Android development (especially Wear!) turned from programming fun to just coping with annoying restrictions and changes introduced by Google. Wear OS 3 is standing on the doorstep, and I'm pretty sure that this will worsen the situation. I don't want to complain at all, Googles position makes good sense to me. But for small open source projects without monetarization all that seems to be too much to cope with...

Let me know in case you need any information.

**Pull request merged**
